version: '3'

volumes:
  php_data:
    name: php_data
    driver: local
networks:
  monitoring:
    name: monitoring

services:

  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring
    ports:
      - 80:80
      - 443:443
    environment:
      - DB_HOST=testdb.cj4me64yy3cc.ap-southeast-1.rds.amazonaws.com #endpoint RDS
      - DB_PORT=3306
      - DB_USERNAME=ltka #master uname
      - DB_PASSWORD=root1234 #master pw

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    networks:
      - monitoring
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST=testdb.cj4me64yy3cc.ap-southeast-1.rds.amazonaws.com 
      - PMA_PORT=3306




